### ISSUE TITLE
Issue with CUDA/GPU run

### ISSUE THREAD

**Issue by MichaelCato** [ELELAB/RaSP_workflow#31]
When I try to run this locally, I get the following error. Can you help me troubleshoot?

Traceback (most recent call last):
  File "/home/cato/RaSP_workflow/RaSP_workflow", line 276, in <module>
    df_ml = ds_pred(cavity_model_net,
  File "/home/cato/RaSP_workflow/src/helpers.py", line 606, in ds_pred
    cavity_pred_batch = cavity_model_net(x_cavity_batch)
  File "/home/cato/localcolabfold/colabfold-conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/cato/RaSP_workflow/src/cavity_model.py", line 309, in forward
    x = self.gaussian_blurring(x)
  File "/home/cato/RaSP_workflow/src/cavity_model.py", line 381, in gaussian_blurring
    torch.arange(atom_type_j_data.shape[0] - 1)[change_mask_j] + 1,
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

**Comment by DegnKristine** [comment]
Hi Michael, 

What are you giving on the -r flag? `-r [RUNTYPE]`, it has to be either cpu or cuda, and i think it is case sensitive, e.g. if you write 'GPU' or 'CUDA' it may not correctly interpret your need, which would make the helpers.py and cavity_model.py scripts fail. 

Let me know :)

**Comment by imabio** [comment]
Hi, in case it is useful, replacing:

```
                ranges_i = torch.cat(
                    [
                        torch.tensor([0]),
                        torch.arange(atom_type_j_data.shape[0] - 1)[change_mask_j] + 1,
                        torch.tensor([atom_type_j_data.shape[0]]),
                    ]
                )
```
with
```
                ranges_i = torch.cat(
                    [
                        torch.tensor([0]).to(change_mask_j.device),
                        torch.arange(atom_type_j_data.shape[0] - 1).to(change_mask_j.device)[change_mask_j] + 1,
                        torch.tensor([atom_type_j_data.shape[0]]).to(change_mask_j.device),
                    ]
                )
```
at [RaSP_workflow/src/cavity_model.py lines 378-384](https://github.com/ELELAB/RaSP_workflow/blob/8ea89342727e7b2f6e5e1823992d0edef71e31eb/src/cavity_model.py#L378-L384) seems to fix this particular issue on my end.

**Comment by mtiberti** [comment]
hi, thank you @imabio , can you tell us what your change accomplishes? I never worked directly on that part of the code. I was just wondering if it's worth opening a PR with this change

**Comment by imabio** [comment]
Hi @mtiberti, 
When running the original code with `-r cuda`, the device for `change_mask_j` is cuda but the device for the rest of the tensors is cpu (the default).

Consistent with this, when using `-r cpu`, the workflow runs to completion.

The modified code just ensures all tensors use the same device.

In retrospect, applying the fix this way would make it more readable:

                ranges_i = torch.cat(
                    [
                        torch.tensor([0]).to(x.device),
                        torch.arange(atom_type_j_data.shape[0] - 1).to(x.device)[change_mask_j] + 1,
                        torch.tensor([atom_type_j_data.shape[0]]).to(x.device),
                    ]
                )

**Comment by pablosanchezizquierdo** [comment]
I close this issue after updating the code with @imabio suggestion. Now all tensors run in the same device when using `-r cpu` or `-r cuda`. Thanks for the suggestion.
